const NavigationRouteNames = {
  HOME: "home",
  APPROVAL: "approval",
  PROFILE: "profile",
  Offers: "offers",
  LOGIN: "login",
  FAQ: "faq",
  FORGOT_PASSWORD: "forgot_password",
  SPLASH_SCREEN: "splash_screen",
  TUTORIAL_SCREEN: "tut_screen",
  OfferDetail: "offer_detail",
  AdvantagesList: "advantages_list",
  AdvantagesDetail: "advantages_detail",
  CHANGE_PASSWORD: "changePassword",
  TimeSheetList: "tmesheet_list",
  TimeSheetDetail: "timesheet_detail",
  REQUEST_FOR_CLAIM: "request_for_claim",
  APPLY_LEAVE: "apply_leave",
  LEAVE: "leave",
  EDUCATION_CLAIM: "education_claim",
  VERIFY_OTP: "verify_otp",
  APPROVAL_OPERA_LIST: "approval_opera_list",
  APPROVAL_SALES_LIST: "approval_slaes_list",
  APPROVAL_FINANCE_LIST: "approval_finance_list",
  APPROVAL_PURCHASE_REQUEST_LIST: "APPROVAL_PURCHASE_REQUEST_LIST",
  APPROVAL_PURCHASE_ORDER_LIST: "APPROVAL_PURCHASE_ORDER_LIST",
  APPROVAL_SALES_DETAIL: "approval_slaes_details",
  APPROVAL_OPERA_DETAIL: "approval_opera_details",
  APPROVAL_MALLS_LIST: "approval_malls_list",
  BIOMETRIC_SETUP: "BiometricSetup",

  PRICE_REQUEST: "PriceRequest",
  CONFIRM_ADDRESS: "AddressConfirm",
  PRICE_CONFIRM: "PriceConfirm",
  PICKUP_DETAILS: "PickupDetails",
  CALL_REQUEST: "CallRequest",
  WORKORDER_DETAILS: "WorkOrderDetails",
  PAYMENT: "Payment",

  NEW_ORDER: "OrderType",
  SELLER_MY_ORDER: 'SellerMyOrder',
  SELLER_ORDER_DETAIL: 'SellerOrderDetail',

  ASSIGN_ORDER: "OrderAssign",
  SIGNUP: "SignUp",
  LOGIN_WITH_EMAIL: "LoginWithEmail",
  HOME_SCREEN: "HomeScreen",
  NEW_ORDER_REQUEST: "New Order",

  CONFIRMATION: "Confirmation",
  WORK_ORDER_CONFIRMATION: "WorkOrderConfirmation",

  ACCOUNT_CREATE: "AccountCreate",
  ORDER_ASSIGN: "OrderAssign",
  ORDER: "Order",
  USERS: "Users",
  PICKUP_ORDER: "PickUpOrder",
  PAYMENT_VERIFICATION: "PaymentVerification",
  WORK_ORDER_VERIFICATION: "WorkOrderVerification",

  ORDER_DETAILS: "OrderDetails",
  WORKORDER_EMAIL: "WorkOrderEmail",
  CALLBACK_CONFIRMATION: "CallBackConfirmation",
  PICKUP_DATE: "PickupDate",
  ENABLEDISABLE_USER: "EnableDisableUser",
  ORDER_FAILED: "OrderFailed",

  ORDER_CONFIRMATION: "OrderConfirmation",
  WAREHOUSE_DETAILS: "WarehouseDetails",
  SCHEDULE_ORDER: "ScheduledOrder",
  AGGREGATOR_SCHEDULE_ORDER_LIST: "ScheduledOrderList",

  INVENTORY: "Inventory",
  RECYCLER_INVENTORY: "RecyclerInventory",
  
  RECYCLER_NEW_ORDER_LIST: "RecyclerNewOrderList",
  RECYCLER_SCHEDULED_ORDER_LIST: "RecyclerScheduleOrderList",
  RECYCLER_WORK_ORDER_LIST: 'RecyclerWorkOrderList',

  NEW_WORKORDER: "NewWorkOrder",
  WORKORDER_SUMMARY: "Workordersummary",
  COMPLETED_ORDER: "CompletedOrder",
  WAREHOUSEORDER_CONFIRMATION: "WarehouseOrderConfirmation",

  PAYMENT_DETAILS: "PaymentDetails",

  UPDATE_PROFILE: "UpdateProfile",
  BUSINESS_DETAIL: "BusinessDetail",
  PROFILE_UPDATE: "ProfileUpdate",
  DOWNLOAD_REPORT: "DownloadReport",
  MANAGE_EPR: "ManageEPR",
  SUBCATEGORY_DETAILS: "SubCategoryDetails",
  PROVISIONAL_PRICING: "ProvisionalPricing",
  SMART_CONTRACT: "SmartContract",
  AUDIT_TRAIL: "AuditTrail",
  SMARTCONTRACT_DETAIL: "SmartContractDetail",
  OWNED_CONTRACTS: "OwnedContracts",
  ADD_SUBUSER: "AddSubUser",
  PASSWORD_RESET: "PasswordReset",
  SMARTCONTRACT_VIEWITEM: "SmartContractViewItem",
  ADMIN_NEW_ORDER_LIST: "AdminNewOrderList",
  ADMIN_NEW_ORDER: "AdminNewOrder",
  AGGREGATOR_NEW_ORDERS: "NewOrders",
  AGGREGATOR_WORK_ORDER_LIST: 'AggregatorWorkOrderList',
  REJECT_ORDER: "RejectOrder",
  PROPOSE_TIME: "ProposeTime",
  ADD_USER: 'AddUser',
  WORK_ORDERDETAIL: "WorkOrderDetail",
};

export default NavigationRouteNames;
