const commonOld = {
  backArrow: require('../../assets/commonOld/backArrow.png'),
  headerSquare: require('../../assets/commonOld/headerSquare.png'),
  userPlaceHolderIcon: require('../../assets/commonOld/userPlaceHolderIcon.png'),
  circularUserPlaceHolder: require('../../assets/commonOld/circularUserPlaceHolder.png'),
  clock: require('../../assets/commonOld/clock.png'),
  document: require('../../assets/commonOld/document.png'),
  blueCheck: require('../../assets/commonOld/blueCheck.png'),
  orangeCheck: require('../../assets/commonOld/orangeCheck.png'),
  blueCheckOne: require('../../assets/commonOld/blueCheckOne.png'),
  cancel: require('../../assets/commonOld/cancel.png'),
  greenCheck: require('../../assets/commonOld/greenCheck.png'),
  userPlaceHolderSquare: require('../../assets/commonOld/userPlaceHolderSquare.png'),
  progressImg: require('../../assets/commonOld/progressImg.png'),
  chevronDown: require('../../assets/commonOld/chevronDown.png'),
  calendar: require('../../assets/commonOld/calendar.png'),
  clear: require('../../assets/commonOld/clear.png'),
  correct: require('../../assets/commonOld/approved.gif'),
  cancelled: require('../../assets/commonOld/cancelled.gif'),
  forward: require('../../assets/commonOld/forward.gif'),
  plus: require('../../assets/commonOld/plus.png'),
  arrowLeft:require('../../assets/common/ArrowLeft.png'),
  search:require('../../assets/common/Search.png'),
};
export default commonOld;
